
// import React from "react";
// import ReactDOM from "react-dom/client" //old way: import ReactDOM from "react-dom"

//index.html (i mean the app.js part) wasnt working so we imported react and react-dom from node_modules, but then wasnt working again so we put type module in script tag of index.html
// import is a part of new ES6 Module System, hence it's not norml JS, it is of type module so add this in index.html
// <script type="module" src="app.js"></script>
//reason: by default browser consider js file as normal JS file not module
//index.html wont run still so type
//type npx parcel index.html
//reason: parcel is a module bundler, it will convert module type code into normal js code which browser can understand
//now ull see the code with app.js code reflected, if still getting error, then remove main file from package.json
//close server : ctrl+c
//dist and parcel-cache folder are auto generated by parcel, do not edit them
//if i delete dist and parcel-cache folder, then also it will work, because parcel will auto generate them again
//but if i delete parcel-cache folder, then next time parcel will take more time to start the server, because it has to generate cache again (built in 300+ ms  else 3-4ms)


//this is still not production ready code, for production ready code we have to build the code
//production ready code goes in dist folder
//delete dist folder first
//now type
//type npx parcel build index.html
//it will create a new folder called build, inside that all the code will be production ready code
//2 files index.html and index.[hash].js will be created in dist folder, a 3rd file .map file will also be created in dist folder
//index.[hash].js is the bundled file which contains all the code of app.js and also the code of react and react-dom and other dependencies
//.[hash] is a unique string generated based on the content of the file
//hash is added to avoid cache problem in browser
//index.html will be written in a single line to reduce the size of file
//and index.[hash].js will also be minified to reduce the size of file
//now if we want to deploy our code, we can deploy the code inside build folder
//mapping file is not needed, rest 2 files u can put in production server, dist folder size will just be around 200kb
//index.[hash].js.map file is used for debugging purpose, it will help to debug the minified code, it can help to map the minified code to original code
//but we dont need it in production, so we can ignore it while deploying
//now if we want to see the production ready code in action, we can use a simple static server
//type npx serve dist
//it will start a server and give a link, open that link in browser to see the production ready code in action



//JSX

import React from "react";
import ReactDOM from "react-dom/client"

const element = React.createElement("h1",{id:"first", className:"Rahul", style:{backgroundColor:"blue", fontSize:"30px", color:"pink"}},"Hello Coder Army");
const element2 = React.createElement("h2",{id:"second", className:"Rahul", style:{backgroundColor:"black", fontSize:"30px", color:"pink"}},"Maja aaya muje");
const div1 = React.createElement('div',{},[element,element2]);
const Reactroot = ReactDOM.createRoot(document.getElementById('root'));

// Reactroot.render(element);
// Reactroot.render(element2);

Reactroot.render(div1);

// instead of creating element like this const element = React.createElement("h1",{id:"first", className:"Rahul", style:{backgroundColor:"blue", fontSize:"30px", color:"pink"}},"Hello Coder Army");, we can
// write it like this using JSX
//now we are not gonna use React.createElement method, instead we will use JSX syntax
//JSX looks like HTML code, but it is not HTML, it is JS code
//Babel will convert this JSX code into React.createElement code
// jsx is not part of react, it is a syntax extension of JS
//facebook devs didnt create jsx, it is created by other devs, but facebook adopted it and made it popular by using it in react

const newElement = <h1> Hello Coder Army </h1>
Reactroot.render(newElement);

//let's see the old way again
// console.log(element); //op: object

// React Element: It is a JS Object which describes what we want to see on the screen
// React Element is not HTML Element, it is a JS Object
// React Element is an object representation of HTML Element
// React Element is created using React.createElement() method

//                     React                               Render
// React.createElement() => gives react element(i.e JSObject) => HTML Element

// React.createElement('h1',{},"Hello Coder Army");

//now the new way using JSX
// const newElement = <h1>Hello Coder Army</h1>

//     babel:                   React                            Render
// JSX => React.createElement() => gives react element(i.e JSObject) => HTML Element

//babel is already integrated with parcel, so we dont have to do anything extra to use babel with parcel, can verify in node_modules folder and see babel related packages
//no need to install babel separately, comes bundled with parcel


//jsx ke andar js ke expression bhi likh sakte ho, bas {} ke andar likhna hai
// JSX: JS ke expression
// const names = "Rohit";
// const obj = {
//     age:23,
//     salary:60
// }

// const obj2 = {
//     backgroundColor:"black",
//     color:"pink",
//     fontSize:"30px"
// }


//what if i wanna write multiple elements, use ( ) these brackets to wrap em in div as newElement expects single element
//bina brackets ke bhi chalega, but better to use brackets for multiple lines for better readability
// // React ELement
// // const newElement = (
// //     <div>
// //          <h1 id="first" className="second" >Hello Coder Army {names}</h1> //write className instead of class as class is reserved word in JS, one difference bw html and jsx
// //          <h2 style={{backgroundColor:"black",color:"white"}}>Maja aaya muje {obj.age}</h2>
// //     </div>
// // ) //will work without brackets also
//isse extra div milri, i can use empty tag also

// const newElement = (
//     <>
//          <h1 id="first" className="second" >Hello Coder Army {names}</h1>
//          <h2 style={obj2}>Maja aaya muje {obj.age}</h2>
//     </>
// ) //will work without brackets also

// then use ReactDOM.createRoot and render method to render it
// const Reactroot = ReactDOM.createRoot(document.getElementById('root'));
// Reactroot.render(newElement);

//i can add my own attributes also like money="23" ab ye to as a string jayega, to send as a number use {}, can send objects also
// <h1 money={23} data-id="101" >Hello Coder Army {names}</h1>
//whererver u see curly braces in jsx {}, it means JS expression is there
//what if i want styling, do in style.css or inline styling also possible
//inline styling me style attribute ke andar ek object dena hota hai
//style={{backgroundColor:"black", color:"white"}}
//in css normally likhte hai background-color, but in jsx camelCase me likhna hota hai backgroundColor
//style attribute me double curly braces {{}} lagega, because pehla {} jsx ke liye hai ki yaha js expression hai, aur dusra {} js object ke liye hai
//many people dont explain this and say it is a syntax of react, but it is not, it is just how jsx works with js objects


// we studied React Element and JSX

// // React Component: react component ek function hota hai jo react element return karta hai
//are of two types
//1. Function Based Component
//2. Class Based Component (old way, ab use nahi hota)

// // function Based Component : ki function kaise likhte hai jo react element return kare bas yahi hai

// function greet(){
//     return <h1>Aur bhai kaisa hai</h1>
// };

// const meet = ()=>{
//     return <h2>Mera sab achaa hai</h2>
// }


// const newElement2 = greet();
// const newElement3 = meet();

// const newElement4 = <>{greet()} {meet()}</>

// // const Reactroot = ReactDOM.createRoot(document.getElementById('root'));

//Reactroot.render(newElement2);
// Reactroot.render(newElement3);
//or
//reactroot.render(greet());
//reactroot.render(meet());

// Reactroot.render(newElement4);
//or
// Reactroot.render(<>{greet()} {meet()}</>);

// // JSX: Javascript XML: HTML code direct js ke andar likh sakte ho







